PROJECT = files 
PROJECT_DESCRIPTION = File storage service around OpenResty and Riak KV.
PROJECT_VERSION = 0.1.0
DEPS = luerl cowboy econfig uuid jsx gun protobuffs riakc meck
dep_cowboy_commit = 2.2.2
ERLC_OPTS = +debug_info
DEP_PLUGINS = cowboy
include erlang.mk
# trying to ident with 4 spaces here.
SP = 4
